on:
  push:
    branches:
      - master
      
      
      
      

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: "login to docker hub"
        run: docker login --username mohamedkozok --password dckr_pat_xN-va3I1T7jKEaBaQvzrQoPVYZk
      - name: 'building docker image'
        run: docker build -t mohamedkozok/myimage .
        
      - name: "pushing to dockerhub"
        run: docker push mohamedkozok/myimage